export const Category = [
  'Artificial Intelligence',
  'Business & Finance',
  'Education',
  'Entertainment',
  'Environment',
  'Fashion',
  'Fitness',
  'Food & Cooking',
  'Geography',
  'Health & Wellness',
  'History',
  'Lifestyle',
  'Marketing',
  'Music',
  'Personal Finance',
  'Photography',
  'Politics',
  'Psychology',
  'Science & Research',
  'Self-Improvement',
  'Spirituality',
  'Sports',
  'Startups',
  'Technology',
  'Travel',
]
